### ISSUE TITLE
按钮文字反了

### ISSUE THREAD

**Issue by TsukuyomiShirabe** [vacuityv/modifyHeaders#1]
我期望的export和import按钮，前者应该输出一个json，后者应该接受一个json作为输入并作为设置，但实际上这两个按钮与我的想法恰好相反

**Comment by vacuityv** [comment]
@TsukuyomiShirabe  确实反了，我明天修复一下，非常感谢你的反馈

**Comment by vacuityv** [comment]
@TsukuyomiShirabe  我已经在最新的 0.0.1.1 版本修复了这个问题，目前已发布，感谢您的反馈
